EmployeeApplication/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('loginPage.urls'))
]

loginPage/urls.py
from django.urls import path
from . import views
app_name='loginPage'

urlpatterns=[path("",views.login,name='login'),
path("login",views.authenticate,name="receive"),
path("login/<int:e_id>",views.employeeIndividualPage,name='Employee'),
path("login/updateEmployee/<int:e_id>",views.updateEmployee,name="updateEmployee"),
path("login/newUserPage",views.newUserPage,name='newUserPage'),
path('login/createNewUser',views.createNewUser,name='createNewUser'),
path('login/logout',views.logout,name='logout'),
path('login/deleteUser/<int:e_id>',views.deleteUser,name='deleteUser'),
path('login/empolyeesPage',views.employeesPage,name='employeesPage'),]

loginPage/models.py
from django.db import models
class AdminUsername(models.Model):
    username=models.CharField(max_length=200)
    def __str__(self):
        return self.username

class AdminPassword(models.Model):
    models.ForeignKey(AdminUsername,on_delete=models.CASCADE)
    password=models.CharField(max_length=200)
    def __str__(self):
        return self.password

class Users(models.Model):
    name=models.CharField(max_length=200)
    phonenumber=models.TextField(max_length=13)
    email=models.EmailField()

loginPage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpRequest
from .models import AdminPassword,AdminUsername,Users
from django.shortcuts import redirect

def getPresentUsers():
    employees=[]
    for e in (Users.objects.all()):
        employees.append([e.id,e.name,e.phonenumber,e.email])
    return employees

def employeesPage(request):
    employees=getPresentUsers()
    return render(request,"employees.html",{'employees':employees})
    

def login(request):
    return render(request,"login.html")

def authenticate(request):
    storedusername=AdminUsername.objects.all().values()[0]['username']
    storedpassword=AdminPassword.objects.all().values()[0]['password']
    USERNAME=request.POST.get("username")
    PASSWORD=request.POST.get("password")
    if storedusername==USERNAME and storedpassword==PASSWORD:
        return redirect('login/empolyeesPage',foo='bar')
        # employees=getPresentUsers()
        # return render(request,"employees.html",{'employees':employees})
    else:
        return render(request,'incorrectCreds.html')

def employeeIndividualPage(request,e_id):
    j=Users.objects.get(pk=e_id)
    return render(request,'Employee.html',{'employee':j})

def updateEmployee(request,e_id):
    employeeID=e_id
    updatedName=request.POST.get('empName')
    updatedNum=request.POST.get('empNum')
    updatedEmail=request.POST.get('empEmail')
    q=Users.objects.get(pk=employeeID)
    q.name=updatedName
    q.phonenumber=updatedNum
    q.email=updatedEmail
    q.save()
    # return redirect()
    employees=getPresentUsers()
    return render(request,"employees.html",{'employees':employees})

def newUserPage(request):
    return render(request,'newUser.html')

def createNewUser(request):
    Name=request.POST.get('Name')
    PhoneNumber=request.POST.get('Number')
    Email=request.POST.get('Email')
    q=Users(name=Name,phonenumber=PhoneNumber,email=Email)
    q.save()
    employees=getPresentUsers()
    return render(request,'employees.html',{'employees':employees})

def logout(request):
    return render(request,'login.html')

def deleteUser(request,e_id):
    u=Users.objects.get(pk=e_id)
    u.delete()
    employee=getPresentUsers()
    return render(request,'employees.html',{'employees':employee})

templates/Employee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Comforter&family=Macondo&family=Neonderthaw&family=Poppins:wght@200;300;400;500&family=Ubuntu:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <style>
        body{
            background-color: #a55c1b;
background-image: linear-gradient(315deg, #a55c1b 0%, #000000 74%);
            font-family: 'poppins';
            height: 95vh;
        }
        form
        {
            padding: 10px;
            color: white;
            font-size: 20px;
        }
        form>*
        {
            margin-top: 25px;
        }
        form input,button
        {
            font-size: 20px;
        }
        button
        {
            background-color: #000000;
background-image: linear-gradient(315deg, #000000 0%, #b82e1f 74%);
            cursor: pointer;
            color: white;
            padding:5px 9px;
            border-radius: 5px;
            font-family: 'Macondo';
        }
        #delete
        {
            background-color: #000000;
background-image: linear-gradient(315deg, #000000 0%, #b82e1f 74%);
            padding: 2px 9px;
            border-radius: 3px;
            color: white;
            text-decoration: none;
            font-family: 'Macondo';
        }
    </style>
</head>
<body>
    {% with e=employee %}
    <form action="{% url 'loginPage:updateEmployee' e.id %}" method="POST">
        {%csrf_token%}
        <div>
            <label for="empID">Employee ID: </label>
        <br>
        <input type="text" name='empID' id='empID' value="{{e.id}}" disabled>
        </div>
        
        <div>
            <label for="empName">Employee Name:</label>
        <br>
        <input type="text" name="empName" id="empName" value="{{e.name}}">
        </div>
        
        <div>
            <label for="empnumber">Employee Number:</label>
            <br>
            <input type="text" name="empNum" id="empNum" value="{{e.phonenumber}}">
        </div>
    
        <div>
            <label for="empemail">Employee Mail:</label>
        <br>
        <input type="Email" name="empEmail" id="empEmail" value="{{e.email}}">
        </div>
        <button type="submit">
            Save Changes
        </button>

        <a href="{%url 'loginPage:deleteUser' e.id %}" id='delete'>Delete User</a>
    </form>
{%endwith%}
</body>
</html>

templates/employees.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link href="https://fonts.googleapis.com/css2?family=Comforter&family=Neonderthaw&family=Poppins:wght@200;300;400;500&family=Ubuntu:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap" rel="stylesheet"> -->
    <link href="https://fonts.googleapis.com/css2?family=Comforter&family=Macondo&family=Neonderthaw&family=Poppins:wght@200;300;400;500&family=Ubuntu:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <style>
    body{
        background-color: #a55c1b;
background-image: linear-gradient(315deg, #a55c1b 0%, #000000 74%);
        font-family: 'poppins';
        height: 95vh;
    }
    #Links
    {
        margin: 0px 10px;
    }
    a
    {
        color:white;
        text-decoration: none;
        margin-bottom: 10px;
        cursor: pointer;
        min-width: 30px;
        min-height: 30px;
        padding: 5px 15px;
        background-color: #000000;
        background-image: linear-gradient(315deg, #000000 0%, #b82e1f 74%);
        font-family: 'Macondo';
    }
    tr
    {
    
    border-radius: 10px;
    color:white;
    }
    td
    {
        padding: 5px;
        border-radius: 5px;
    }
    th
    {
        padding: 5px;
    }
    </style>
</head>
<body>
    <div id='Links'>
        <a href="{% url 'loginPage:newUserPage' %}">Create New User</a>
        <a href="{%url 'loginPage:logout' %}">Logout</a>
    </div>
    
    <table style="width: 100%;text-align:center;margin-top:10px">
        <tr>
            <th>Employee ID</th>
            <th>Name</th>
            <th>Phone Number</th>
            <th>Email</th>
        </tr>
    {%for e in employees%}
        <tr>
            <td>
                <a href="{% url 'loginPage:Employee' e.0 %}" style="width: 100%;">{{e.0}}</a>
            </td>
            <td>{{e.1}}</td>
            <td>{{e.2}}</td>
            <td>{{e.3}}</td>
        </tr>
    {%endfor%}
</table>
</body>
</html>

templates/incorrectCreds.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Incorrect Credentials!</h1>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link href="https://fonts.googleapis.com/css2?family=Comforter&family=Neonderthaw&family=Poppins:wght@200;300;400;500&family=Ubuntu:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap" rel="stylesheet"> -->
    <link href="https://fonts.googleapis.com/css2?family=Comforter&family=Macondo&family=Neonderthaw&family=Poppins:wght@200;300;400;500&family=Ubuntu:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <style>
        body
        {
            font-family: 'Macondo';
            height: 82vh;
            background-color: #a55c1b;
background-image: linear-gradient(315deg, #a55c1b 0%, #000000 74%);;
        }
        .logo
        {
            text-align: center;
            font-weight: bold;
        }
        .mainContent
        {
            color: white;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            
            padding:100px 25px;
            margin: auto;
            text-align: center;
            width:300px;
            font-size: 30px;
            border-radius: 5px;
            margin-top: 100px;
        }
        .mainContent input,button
        {
            font-family: 'Macondo';
            font-size: 15px;
            margin-top: 10px;
            border-radius: 2px;
            outline: 0px;
            border: 0px;
            padding: 5px 5px;
        }
        button
        {
            width: 100%;
            cursor: pointer;
            letter-spacing: 2px;
            background: #2A2550;
            color: white;
        }
    </style>
</head>
<body>
    <div class="mainContent">
        <div class="logo">
            WELCOME
        </div>
        <form action="/login" method="POST">
            {%csrf_token%}
            <input type="text" name="username" id="username" placeholder="User Name">
            <br>
            <input type="password" name="password" id="password" placeholder="password">
            <br>
            <button type="submit">LOGIN</button>
        </form>
    </div>
</body>
</html>

templates/newUser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link href="https://fonts.googleapis.com/css2?family=Comforter&family=Neonderthaw&family=Poppins:wght@200;300;400;500&family=Ubuntu:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap" rel="stylesheet"> -->
    <link href="https://fonts.googleapis.com/css2?family=Comforter&family=Macondo&family=Neonderthaw&family=Poppins:wght@200;300;400;500&family=Ubuntu:ital,wght@0,300;0,400;0,500;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <style>
        body{
            background-color: #a55c1b;
background-image: linear-gradient(315deg, #a55c1b 0%, #000000 74%);
            font-family: 'poppins';
            color: white;
            min-height: 95vh;
            font-family: 'Macondo';
        }
        form
        {
            padding: 10px;
            color: white;
            font-size: 20px;
        }
        form>*
        {
            margin-top: 25px;
        }
        form input,button
        {
            font-size: 20px;
        }
        button
        {
            font-family: 'Macondo';
            cursor:pointer;
            letter-spacing: 1px;
            background-color: #000000;
            background-image: linear-gradient(315deg, #000000 0%, #b82e1f 74%);
            color: white;
            border-radius: 5px;
            padding: 5px;
        }
        
    </style>
</head>
<body>
    <h1>Create User</h1>
    <form action="createNewUser" method="POST">
        {%csrf_token%}
        <div>
            <label for="Name">Employee Name</label>
        <br>
        <input type="text" name="Name" id="Name" placeholder="EmployeeName">
        </div>
        <div>
            <label for="number">Phone number</label>
        <br>
        <input type="number" name="Number" id="Number" placeholder="Phone number" maxlength="13" >
        </div>
        <div>
            <label for="email">Email</label>
            <br>
            <input type="email" name="Email" id="Email" placeholder="Email">
        </div>
        <button type="submit">Create New User</button>
    </form>
</body>
</html>